# Generated by Django 5.2.15 on 2026-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='moderation_action',
            field=models.CharField(blank=True, choices=[('HIDE', 'Hidden for investigation'), ('BLOCK', 'Blocked for legal violation')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_action',
            field=models.CharField(blank=True, choices=[('HIDE', 'Hidden for investigation'), ('BLOCK', 'Blocked for legal violation')], max_length=10, null=True),
        ),
    ]
