# Generated by Django 5.2.15 on 2026-09-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_what_is_already_on_sale(apps, schema_editor):
    """Every listing that existed before review was introduced counts as approved.

    They have been on sale, in some cases for months. Dropping them all into the queue would
    take the whole catalogue off the shopper side at once and punish stalls for a rule that
    did not exist when they wrote the listing. Review starts applying to what comes next.
    """
    Product = apps.get_model("catalog", "Product")
    Product.objects.all().update(review_status="APPROVED")


def noop(apps, schema_editor):
    """Nothing to undo: the columns go with the reverse of the operations above."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalcustomerprofile'),
        ('catalog', '0005_category_unique_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Waiting for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Waiting for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['review_status', 'created_at'], name='prod_review_idx'),
        ),
        migrations.RunPython(approve_what_is_already_on_sale, noop),
    ]
