# Generated by Django 5.2.15 on 2026-09-27 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalcustomerprofile'),
        ('catalog', '0007_produce_icons_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='max_per_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_per_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('max_per_order__isnull', True), models.Q(('max_per_order__gte', 1), ('max_per_order__lte', 999)), _connector='OR'), name='prod_max_per_order_range'),
        ),
    ]
