# Generated by Django 5.2.15 on 2026-09-27 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalcustomerprofile'),
        ('catalog', '0008_product_max_per_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='min_per_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='min_per_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_per_order__gte', 1), ('min_per_order__lte', 999), models.Q(('max_per_order__isnull', True), ('min_per_order__lte', models.F('max_per_order')), _connector='OR')), name='prod_min_per_order_range'),
        ),
    ]
