# Generated by Django 5.2.15 on 2026-09-27 12:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Starting points in USD per unit; admins tune them on the Price guidelines page. A category
# created later simply has no guideline until an admin adds one (the peer-median check still runs).
DEFAULT_GUIDELINES = {
    "Vegetables": {"KG": ("0.20", "20.00", 5000), "BUNCH": ("0.10", "10.00", 5000), "PIECE": ("0.05", "15.00", 10000), "PACK": ("0.20", "30.00", 5000)},
    "Fruits": {"KG": ("0.30", "60.00", 5000), "BUNCH": ("0.20", "20.00", 5000), "PIECE": ("0.05", "40.00", 10000), "PACK": ("0.30", "60.00", 5000)},
    "Dairy & Eggs": {"KG": ("0.50", "60.00", 2000), "BUNCH": ("0.50", "20.00", 2000), "PIECE": ("0.05", "10.00", 20000), "PACK": ("0.50", "40.00", 5000)},
    "Bakery": {"KG": ("0.50", "50.00", 1000), "BUNCH": ("0.30", "20.00", 1000), "PIECE": ("0.10", "30.00", 5000), "PACK": ("0.30", "40.00", 2000)},
    "Spices": {"KG": ("0.50", "200.00", 1000), "BUNCH": ("0.05", "10.00", 5000), "PIECE": ("0.05", "20.00", 5000), "PACK": ("0.20", "50.00", 5000)},
    "Others": {"KG": ("0.10", "200.00", 5000), "BUNCH": ("0.05", "100.00", 5000), "PIECE": ("0.05", "100.00", 10000), "PACK": ("0.05", "100.00", 5000)},
}


def seed_guidelines(apps, schema_editor):
    from decimal import Decimal

    Category = apps.get_model("catalog", "Category")
    PriceGuideline = apps.get_model("catalog", "PriceGuideline")
    for category in Category.objects.all():
        units = DEFAULT_GUIDELINES.get(category.name)
        if not units:
            continue
        for unit, (low, high, max_stock) in units.items():
            PriceGuideline.objects.get_or_create(
                category=category,
                unit=unit,
                defaults={"min_price": Decimal(low), "max_price": Decimal(high), "max_stock": max_stock},
            )


def noop(apps, schema_editor):
    """The table goes with the reverse of CreateModel."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_min_per_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('PIECE', 'Piece'), ('PACK', 'Pack')], max_length=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_guidelines', to='catalog.category')),
            ],
            options={
                'db_table': 'price_guidelines',
                'ordering': ['category__display_order', 'category__name', 'unit'],
                'constraints': [models.UniqueConstraint(fields=('category', 'unit'), name='price_guideline_uniq'), models.CheckConstraint(condition=models.Q(('max_price__lte', Decimal('10000.00')), ('min_price__gte', Decimal('0.01')), ('min_price__lte', models.F('max_price'))), name='price_guideline_range')],
            },
        ),
        migrations.CreateModel(
            name='ProductAIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('LISTING', 'New or edited listing'), ('WEEKLY_IMAGE', 'Weekly photo check')], max_length=15)),
                ('content_hash', models.CharField(max_length=64)),
                ('verdict', models.CharField(choices=[('PASS', 'Nothing found'), ('NEEDS_REVIEW', 'Worth a closer look'), ('LIKELY_VIOLATION', 'Likely breaks the rules'), ('UNAVAILABLE', 'AI check unavailable')], max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('findings', models.JSONField(default=list)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_error', models.CharField(blank=True, max_length=300, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('rules_version', models.CharField(blank=True, default='', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_decision', models.CharField(blank=True, choices=[('PENDING', 'Waiting for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('admin_decided_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='catalog.product')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category')),
            ],
            options={
                'db_table': 'product_ai_reviews',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'kind', '-created_at'], name='ai_review_latest_idx'), models.Index(fields=['verdict', 'created_at'], name='ai_review_verdict_idx')],
            },
        ),
        migrations.RunPython(seed_guidelines, noop),
    ]
