# Generated by Django 5.2.15 on 2026-09-28 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_ai_listing_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productaireview',
            name='admin_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaireview',
            name='admin_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productaireview',
            name='auto_action',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved by AI'), ('HELD', 'Held by AI')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productaireview',
            name='auto_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
