# Generated by Django 5.2.15 on 2026-09-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ai_auto_decisions'),
        ('markets', '0005_farmermarket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMarketExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exclusions', to='markets.farmermarket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_exclusions', to='catalog.product')),
            ],
            options={
                'db_table': 'product_market_exclusions',
                'constraints': [models.UniqueConstraint(fields=('product', 'farmer_market'), name='pme_uniq_product_stall')],
            },
        ),
    ]
