# Generated by Django 5.2.15 on 2026-09-28 19:37

from django.db import migrations, models

# "Piece" was left over from the bakery category; produce sold one by one is "each" (trái / quả).
MODELS = ("Product", "HistoricalProduct", "PriceGuideline")


def piece_to_each(apps, schema_editor):
    # Guidelines of a category that is gone (an old seed truncated categories with foreign key
    # checks off) break the update below and can never be used; drop them first.
    Category = apps.get_model("catalog", "Category")
    apps.get_model("catalog", "PriceGuideline").objects.exclude(
        category_id__in=Category.objects.values("id")
    ).delete()
    for name in MODELS:
        apps.get_model("catalog", name).objects.filter(unit="PIECE").update(unit="EACH")


def each_to_piece(apps, schema_editor):
    for name in MODELS:
        apps.get_model("catalog", name).objects.filter(unit="EACH").update(unit="PIECE")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('EACH', 'Each'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='priceguideline',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('EACH', 'Each'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('EACH', 'Each'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10),
        ),
        migrations.RunPython(piece_to_each, each_to_piece),
    ]
