# Generated by Django 5.2.15 on 2026-09-26 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalcustomerprofile'),
        ('markets', '0002_historicalfarmerclosure_historicalfarmermarket_and_more'),
        ('orders', '0004_historicalorder_historicalorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pickup_date'], name='ord_pickup_date_idx'),
        ),
    ]
