# Generated by Django 5.2.15 on 2026-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_ord_pickup_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
