# Generated by Django 5.2.15 on 2026-09-28 19:37

from django.db import migrations, models

# Order lines keep the unit they were bought in; rename the old "piece" code with the catalog (0014).
MODELS = ("OrderItem", "HistoricalOrderItem")


def piece_to_each(apps, schema_editor):
    for name in MODELS:
        apps.get_model("orders", name).objects.filter(unit="PIECE").update(unit="EACH")


def each_to_piece(apps, schema_editor):
    for name in MODELS:
        apps.get_model("orders", name).objects.filter(unit="EACH").update(unit="PIECE")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_reschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('EACH', 'Each'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('BUNCH', 'Bunch'), ('EACH', 'Each'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10),
        ),
        migrations.RunPython(piece_to_each, each_to_piece),
    ]
