# Generated by Django 5.2.15 on 2026-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalcustomerprofile'),
        ('markets', '0004_farmermarket_many_markets_per_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermarket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for approval'), ('APPROVED', 'Approved')], default='APPROVED', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalfarmermarket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for approval'), ('APPROVED', 'Approved')], default='APPROVED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='farmermarket',
            index=models.Index(fields=['status'], name='fm_status_idx'),
        ),
    ]
