# Generated by Django 5.2.15 on 2026-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_no_show_auto_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_REGISTERED', 'Account Registered'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Change Password'), ('ACCESS_DENIED', 'Access Denied'), ('EXPORT_DATA', 'Export Data'), ('FARMER_APPROVED', 'Approve Farmer'), ('FARMER_REJECTED', 'Reject Farmer'), ('FARMER_SUSPENDED', 'Suspend Farmer'), ('FARMER_REINSTATED', 'Reinstate Farmer'), ('CUSTOMER_DEACTIVATED', 'Deactivate Customer'), ('CUSTOMER_ACTIVATED', 'Activate Customer'), ('CUSTOMER_AUTO_LOCKED', 'Auto-lock Customer (No-shows)'), ('PRODUCT_HIDDEN', 'Hide Product'), ('PRODUCT_RESTORED', 'Restore Product'), ('PRODUCT_APPROVED', 'Approve Product'), ('PRODUCT_REJECTED', 'Reject Product'), ('PRODUCT_BLOCKED', 'Block Product'), ('PRODUCT_UNBLOCKED', 'Unblock Product'), ('REVIEW_HIDDEN', 'Hide Review'), ('REVIEW_RESTORED', 'Restore Review'), ('MARKET_CREATED', 'Create Market'), ('MARKET_UPDATED', 'Update Market'), ('MARKET_DEACTIVATED', 'Deactivate Market'), ('MARKET_ACTIVATED', 'Activate Market'), ('STALL_MARKET_APPROVED', 'Approve Market Registration'), ('STALL_MARKET_REJECTED', 'Refuse Market Registration'), ('FARMER_UPDATED', 'Update Farmer Profile'), ('CUSTOMER_UPDATED', 'Update Customer Profile'), ('ACCOUNT_PURGED', 'Purge Stale Accounts'), ('CONTENT_FLAGGED', 'Flag Content For Review'), ('CONTENT_FLAG_RESOLVED', 'Resolve Flagged Content')], max_length=40),
        ),
    ]
