import {
  Apple,
  Banana,
  Bean,
  Beef,
  Carrot,
  Cherry,
  Citrus,
  Croissant,
  Drumstick,
  Egg,
  Fish,
  Flame,
  Flower2,
  Grape,
  Ham,
  Leaf,
  LeafyGreen,
  Milk,
  Nut,
  Salad,
  Shell,
  ShoppingBasket,
  Soup,
  Sprout,
  TreePine,
  Vegan,
  Wheat,
} from 'lucide-react';
import {
  GiAlmond,
  GiAsparagus,
  GiAvocado,
  GiBamboo,
  GiBeet,
  GiBellPepper,
  GiBowlOfRice,
  GiBroccoli,
  GiButter,
  GiCabbage,
  GiCactus,
  GiCheeseWedge,
  GiChicken,
  GiCoconuts,
  GiCoffeeBeans,
  GiCorn,
  GiCow,
  GiCrab,
  GiDuck,
  GiFlowerPot,
  GiFruitBowl,
  GiFruitTree,
  GiGarlic,
  GiGoat,
  GiHerbsBundle,
  GiHoneyJar,
  GiHoneycomb,
  GiHops,
  GiKiwiFruit,
  GiLeek,
  GiLemon,
  GiLotus,
  GiMushroomGills,
  GiNestEggs,
  GiOat,
  GiOlive,
  GiOrange,
  GiOyster,
  GiPalmTree,
  GiPeach,
  GiPeanut,
  GiPear,
  GiPeas,
  GiPig,
  GiPineapple,
  GiPlantSeed,
  GiPotato,
  GiPumpkin,
  GiRabbit,
  GiRaspberry,
  GiSesame,
  GiSheep,
  GiShrimp,
  GiSquid,
  GiStrawberry,
  GiSugarCane,
  GiSunflower,
  GiTomato,
  GiVineLeaf,
  GiWatermelon,
} from 'react-icons/gi';

const ICONS = {
  apple: Apple,
  banana: Banana,
  basket: ShoppingBasket,
  bean: Bean,
  beef: Beef,
  carrot: Carrot,
  cherry: Cherry,
  chilli: Flame,
  citrus: Citrus,
  croissant: Croissant,
  drumstick: Drumstick,
  egg: Egg,
  fish: Fish,
  flower: Flower2,
  grape: Grape,
  ham: Ham,
  leaf: Leaf,
  'leafy-green': LeafyGreen,
  milk: Milk,
  nut: Nut,
  salad: Salad,
  seafood: Shell,
  seedling: Sprout,
  soup: Soup,
  tree: TreePine,
  vegan: Vegan,
  wheat: Wheat,
  almond: GiAlmond,
  asparagus: GiAsparagus,
  avocado: GiAvocado,
  bamboo: GiBamboo,
  beet: GiBeet,
  'bell-pepper': GiBellPepper,
  broccoli: GiBroccoli,
  butter: GiButter,
  cabbage: GiCabbage,
  cactus: GiCactus,
  cattle: GiCow,
  cheese: GiCheeseWedge,
  coconut: GiCoconuts,
  coffee: GiCoffeeBeans,
  corn: GiCorn,
  crab: GiCrab,
  duck: GiDuck,
  'fruit-bowl': GiFruitBowl,
  'fruit-tree': GiFruitTree,
  garlic: GiGarlic,
  goat: GiGoat,
  herbs: GiHerbsBundle,
  honey: GiHoneyJar,
  honeycomb: GiHoneycomb,
  hops: GiHops,
  kiwi: GiKiwiFruit,
  leek: GiLeek,
  lemon: GiLemon,
  lotus: GiLotus,
  mushroom: GiMushroomGills,
  oat: GiOat,
  olive: GiOlive,
  orange: GiOrange,
  oyster: GiOyster,
  palm: GiPalmTree,
  peach: GiPeach,
  peanut: GiPeanut,
  pear: GiPear,
  peas: GiPeas,
  pig: GiPig,
  pineapple: GiPineapple,
  potato: GiPotato,
  'potted-plant': GiFlowerPot,
  poultry: GiChicken,
  pumpkin: GiPumpkin,
  'quail-eggs': GiNestEggs,
  rabbit: GiRabbit,
  raspberry: GiRaspberry,
  rice: GiBowlOfRice,
  seeds: GiPlantSeed,
  sesame: GiSesame,
  sheep: GiSheep,
  shrimp: GiShrimp,
  squid: GiSquid,
  strawberry: GiStrawberry,
  'sugar-cane': GiSugarCane,
  sunflower: GiSunflower,
  tomato: GiTomato,
  'vine-leaf': GiVineLeaf,
  watermelon: GiWatermelon,
};

const LEGACY_ALIASES = {
  pepper: 'chilli',
  flame: 'chilli',
  cake: 'croissant',
  cookie: 'croissant',
  donut: 'croissant',
  sandwich: 'croissant',
  pizza: 'croissant',
  candy: 'nut',
  popcorn: 'wheat',
  dessert: 'milk',
  'ice-cream': 'milk',
  juice: 'citrus',
  beer: 'wheat',
  wine: 'grape',
  cocktail: 'citrus',
  'egg-fried': 'egg',
  utensils: 'basket',
};

function normalise(icon) {
  const key = (icon ?? '').trim().toLowerCase();
  return LEGACY_ALIASES[key] ?? key;
}

export function resolveCategoryIcon(icon) {
  return ICONS[normalise(icon)] ?? Leaf;
}

export const CATEGORY_ICON_NAMES = Object.keys(ICONS);

export function categoryIconLabel(icon) {
  const words = normalise(icon).replaceAll('-', ' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
}
